<a href="https://colab.research.google.com/github/207r1a6654/207r1a6654/blob/main/flatten.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
a=np.array([[1,4,7],[2,5,8],[3,6,9]])
b=a.flatten()
print(b)
c=a.flatten('C')
print(c)
d=a.flatten('F')
print(d)
e=a.flatten('A')
print(e)
f=a.flatten('K')
print(f)

[1 4 7 2 5 8 3 6 9]
[1 4 7 2 5 8 3 6 9]
[1 2 3 4 5 6 7 8 9]
[1 4 7 2 5 8 3 6 9]
[1 4 7 2 5 8 3 6 9]
