<a href="https://colab.research.google.com/github/207r1a6654/207r1a6654/blob/main/numpy1%2C2%2C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
a=np.array([1,3,5,6],dtype=complex)
print(a)

[1.+0.j 3.+0.j 5.+0.j 6.+0.j]
