<a href="https://colab.research.google.com/github/207r1a6654/207r1a6654/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))


[1 2 3]
<class 'numpy.ndarray'>


In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
import numpy as np
a=np.array([1,3,5,6],dtype=complex)
print(a)

[1.+0.j 3.+0.j 5.+0.j 6.+0.j]


In [9]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a.ndim)
print(a.itemsize,"bytes")
print(a.size,"bytes")
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2
8 bytes
10 bytes
(2, 5)


In [11]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a)
a=a.reshape(2,3)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [12]:
import numpy as np
a=np.array([1,2,3,5,15,7])
print(a)
print("The maximum element in the array is:",a.max())
print("The minimum element in the array is:",a.min())
print("The sum of elements in the array is:",a.sum())


[ 1  2  3  5 15  7]
The maximum element in the array is: 15
The minimum element in the array is: 1
The sum of elements in the array is: 33


In [13]:
import numpy as np
a=np.array([[1,2,30],[10,15,4]])
print("The array is:",a)
print("The maximum element in each row:",a.max(axis=1))
print("the maximum element of each coloumn:",a.max(axis=0))
print("The minimum element in each row:",a.min(axis=1))
print("the minimum element of each coloumn:",a.min(axis=0))
print("The sum of all elements in each row",a.sum(axis=1))
print("The sum of all elements in each coloumn",a.sum(axis=0))

The array is: [[ 1  2 30]
 [10 15  4]]
The maximum element in each row: [30 15]
the maximum element of each coloumn: [10 15 30]
The minimum element in each row: [1 4]
the minimum element of each coloumn: [1 2 4]
The sum of all elements in each row [33 29]
The sum of all elements in each coloumn [11 17 34]
